INSERT INTO departamentos VALUES
(DEFAULT, 'Antioquia'),
(DEFAULT, 'Atlantico'),
(DEFAULT, 'Santa Fe de Bogotá D.C.'),
(DEFAULT, 'Bolivar'),
(DEFAULT, 'Boyaca'),
(DEFAULT, 'Caldas'),
(DEFAULT, 'Caqueta'),
(DEFAULT, 'Cauca'),
(DEFAULT, 'Cesar'),
(DEFAULT, 'Cordova'),
(DEFAULT, 'Cundinamarca'),
(DEFAULT, 'Choco'),
(DEFAULT, 'Huila'),
(DEFAULT, 'La Guajira'),
(DEFAULT, 'Magdalena'),
(DEFAULT, 'Meta'),
(DEFAULT, 'Nariño'),
(DEFAULT, 'Norte de Santander'),
(DEFAULT, 'Quindio'),
(DEFAULT, 'Risaralda'),
(DEFAULT, 'Santander'),
(DEFAULT, 'Sucre'),
(DEFAULT, 'Tolima'),
(DEFAULT, 'Valle del Cauca'),
(DEFAULT, 'Arauca'),
(DEFAULT, 'Casanare'),
(DEFAULT, 'Putumayo'),
(DEFAULT, 'San Andres'),
(DEFAULT, 'Amazonas'),
(DEFAULT, 'Guainia'),
(DEFAULT, 'Guaviare'),
(DEFAULT, 'Vaupes'),
(DEFAULT, 'Vichada');

INSERT INTO municipios VALUES
(DEFAULT, 'Medellin', 1),
(DEFAULT, 'Abejorral', 1),
(DEFAULT, 'Abriaqui', 1),
(DEFAULT, 'Alejandria', 1),
(DEFAULT, 'Amaga', 1),
(DEFAULT, 'Amalfi', 1),
(DEFAULT, 'Andes', 1),
(DEFAULT, 'Angelopolis', 1),
(DEFAULT, 'Angostura', 1),
(DEFAULT, 'Anori', 1),
(DEFAULT, 'Antioquia', 1),
(DEFAULT, 'Anza', 1),
(DEFAULT, 'Apartado', 1),
(DEFAULT, 'Arboletes', 1),
(DEFAULT, 'Argelia', 1),
(DEFAULT, 'Armenia', 1),
(DEFAULT, 'Barbosa', 1),
(DEFAULT, 'Belmira', 1),
(DEFAULT, 'Bello', 1),
(DEFAULT, 'Betania', 1),
(DEFAULT, 'Betulia', 1),
(DEFAULT, 'Bolivar', 1),
(DEFAULT, 'Briceño', 1),
(DEFAULT, 'Buritica', 1),
(DEFAULT, 'Caceres', 1),
(DEFAULT, 'Caicedo', 1),
(DEFAULT, 'Caldas', 1),
(DEFAULT, 'Campamento', 1),
(DEFAULT, 'Cañasgordas', 1),
(DEFAULT, 'Caracoli', 1),
(DEFAULT, 'Caramanta', 1),
(DEFAULT, 'Carepa', 1),
(DEFAULT, 'Carmen de Viboral', 1),
(DEFAULT, 'Carolina', 1),
(DEFAULT, 'Caucasia', 1),
(DEFAULT, 'Chigorodo', 1),
(DEFAULT, 'Cisneros', 1),
(DEFAULT, 'Cocorna', 1),
(DEFAULT, 'Concepcion', 1),
(DEFAULT, 'Concordia', 1),
(DEFAULT, 'Copacabana', 1),
(DEFAULT, 'Dabeiba', 1),
(DEFAULT, 'Don Matias', 1),
(DEFAULT, 'Ebejico', 1),
(DEFAULT, 'El Bagre', 1),
(DEFAULT, 'Entrerrios', 1),
(DEFAULT, 'Envigado', 1),
(DEFAULT, 'Fredonia', 1),
(DEFAULT, 'Frontino', 1),
(DEFAULT, 'Giraldo', 1),
(DEFAULT, 'Girardota', 1),
(DEFAULT, 'Gomez Plata', 1),
(DEFAULT, 'Granada', 1),
(DEFAULT, 'Guadalupe', 1),
(DEFAULT, 'Guarne', 1),
(DEFAULT, 'Guatape', 1),
(DEFAULT, 'Heliconia', 1),
(DEFAULT, 'Hispania', 1),
(DEFAULT, 'Itagui', 1),
(DEFAULT, 'Ituango', 1),
(DEFAULT, 'Jardin', 1),
(DEFAULT, 'Jerico', 1),
(DEFAULT, 'La Ceja', 1),
(DEFAULT, 'La Estrella', 1),
(DEFAULT, 'La Pintada', 1),
(DEFAULT, 'La Union', 1),
(DEFAULT, 'Liborina', 1),
(DEFAULT, 'Maceo', 1),
(DEFAULT, 'Marinilla', 1),
(DEFAULT, 'Montebello', 1),
(DEFAULT, 'Murindo', 1),
(DEFAULT, 'Mutata', 1),
(DEFAULT, 'Nariño', 1),
(DEFAULT, 'Necocli', 1),
(DEFAULT, 'Nechi', 1),
(DEFAULT, 'Olaya', 1),
(DEFAULT, 'Peñol', 1),
(DEFAULT, 'Peque', 1),
(DEFAULT, 'Pueblorrico', 1),
(DEFAULT, 'Puerto Berrio', 1),
(DEFAULT, 'Puerto Nare', 1),
(DEFAULT, 'Puerto Triunfo', 1),
(DEFAULT, 'Remedios', 1),
(DEFAULT, 'Retiro', 1),
(DEFAULT, 'Rionegro', 1),
(DEFAULT, 'Sabanalarga', 1),
(DEFAULT, 'Sabaneta', 1),
(DEFAULT, 'Salgar', 1),
(DEFAULT, 'San Andres', 1),
(DEFAULT, 'San Carlos', 1),
(DEFAULT, 'San Francisco', 1),
(DEFAULT, 'San Jeronimo', 1),
(DEFAULT, 'San Jose de La Montaña', 1),
(DEFAULT, 'San Juan de Uraba', 1),
(DEFAULT, 'San Luis', 1),
(DEFAULT, 'San Pedro', 1),
(DEFAULT, 'San Pedro de Uraba', 1),
(DEFAULT, 'San Rafael', 1),
(DEFAULT, 'San Roque', 1),
(DEFAULT, 'San Vicente', 1),
(DEFAULT, 'Santa Barbara', 1),
(DEFAULT, 'Santa Rosa de Osos', 1),
(DEFAULT, 'Santo Domingo', 1),
(DEFAULT, 'Santuario', 1),
(DEFAULT, 'Segovia', 1),
(DEFAULT, 'Sonson', 1),
(DEFAULT, 'Sopetran', 1),
(DEFAULT, 'Tamesis', 1),
(DEFAULT, 'Taraza', 1),
(DEFAULT, 'Tarso', 1),
(DEFAULT, 'Titiribi', 1),
(DEFAULT, 'Toledo', 1),
(DEFAULT, 'Turbo', 1),
(DEFAULT, 'Uramita', 1),
(DEFAULT, 'Urrao', 1),
(DEFAULT, 'Valdivia', 1),
(DEFAULT, 'Valparaiso', 1),
(DEFAULT, 'Vegachi', 1),
(DEFAULT, 'Venecia', 1),
(DEFAULT, 'Vigia del Fuerte', 1),
(DEFAULT, 'Yali', 1),
(DEFAULT, 'Yarumal', 1),
(DEFAULT, 'Yolombo', 1),
(DEFAULT, 'Yondo', 1),
(DEFAULT, 'Zaragoza', 1),
(DEFAULT, 'Barranquilla', 2),
(DEFAULT, 'Baranoa', 2),
(DEFAULT, 'Campo de La Cruz', 2),
(DEFAULT, 'Candelaria', 2),
(DEFAULT, 'Galapa', 2),
(DEFAULT, 'Juan de Acosta', 2),
(DEFAULT, 'Luruaco', 2),
(DEFAULT, 'Malambo', 2),
(DEFAULT, 'Manati', 2),
(DEFAULT, 'Palmar de Varela', 2),
(DEFAULT, 'Piojo', 2),
(DEFAULT, 'Polo Nuevo', 2),
(DEFAULT, 'Ponedera', 2),
(DEFAULT, 'Puerto Colombia', 2),
(DEFAULT, 'Repelon', 2),
(DEFAULT, 'Sabanagrande', 2),
(DEFAULT, 'Sabanalarga', 2),
(DEFAULT, 'Santa Lucia', 2),
(DEFAULT, 'Santo Tomas', 2),
(DEFAULT, 'Soledad', 2),
(DEFAULT, 'Suan', 2),
(DEFAULT, 'Tubara', 2),
(DEFAULT, 'Usiacuri', 2),
(DEFAULT, 'Santa Fe de Bogotá', 3),
(DEFAULT, 'Usaquen', 3),
(DEFAULT, 'Chapinero', 3),
(DEFAULT, 'Santa Fe', 3),
(DEFAULT, 'San Cristobal', 3),
(DEFAULT, 'Usme', 3),
(DEFAULT, 'Tunjuelito', 3),
(DEFAULT, 'Bosa', 3),
(DEFAULT, 'Kennedy', 3),
(DEFAULT, 'Fontibon', 3),
(DEFAULT, 'Engativa', 3),
(DEFAULT, 'Suba', 3),
(DEFAULT, 'Barrios Unidos', 3),
(DEFAULT, 'Teusaquillo', 3),
(DEFAULT, 'Martires', 3),
(DEFAULT, 'Antonio Nariño', 3),
(DEFAULT, 'Puente Aranda', 3),
(DEFAULT, 'Candelaria', 3),
(DEFAULT, 'Rafael Uribe', 3),
(DEFAULT, 'Ciudad Bolivar', 3),
(DEFAULT, 'Sumapaz', 3),
(DEFAULT, 'Cartagena', 4),
(DEFAULT, 'Achi', 4),
(DEFAULT, 'Altos del Rosario', 4),
(DEFAULT, 'Arenal', 4),
(DEFAULT, 'Arjona', 4),
(DEFAULT, 'Arroyohondo', 4),
(DEFAULT, 'Barranco de Loba', 4),
(DEFAULT, 'Calamar', 4),
(DEFAULT, 'Cantagallo', 4),
(DEFAULT, 'Cicuco', 4),
(DEFAULT, 'Cordoba', 4),
(DEFAULT, 'Clemencia', 4),
(DEFAULT, 'El Carmen de Bolivar', 4),
(DEFAULT, 'El Guamo', 4),
(DEFAULT, 'El Peñon', 4),
(DEFAULT, 'Hatillo de Loba', 4),
(DEFAULT, 'Magangue', 4),
(DEFAULT, 'Mahates', 4),
(DEFAULT, 'Margarita', 4),
(DEFAULT, 'Maria La Baja', 4),
(DEFAULT, 'Montecristo', 4),
(DEFAULT, 'Mompos', 4),
(DEFAULT, 'Morales', 4),
(DEFAULT, 'Pinillos', 4),
(DEFAULT, 'Regidor', 4),
(DEFAULT, 'Rio Viejo', 4),
(DEFAULT, 'San Cristobal', 4),
(DEFAULT, 'San Estanislao', 4),
(DEFAULT, 'San Fernando', 4),
(DEFAULT, 'San Jacinto', 4),
(DEFAULT, 'San Jacinto del Cauca', 4),
(DEFAULT, 'San Juan Nepomuceno', 4),
(DEFAULT, 'San Martin de Loba', 4),
(DEFAULT, 'San Pablo', 4),
(DEFAULT, 'Santa Catalina', 4),
(DEFAULT, 'Santa Rosa', 4),
(DEFAULT, 'Santa Rosa Del Sur', 4),
(DEFAULT, 'Simiti', 4),
(DEFAULT, 'Soplaviento', 4),
(DEFAULT, 'Talaigua Nuevo', 4),
(DEFAULT, 'Tiquisio', 4),
(DEFAULT, 'Turbaco', 4),
(DEFAULT, 'Turbana', 4),
(DEFAULT, 'Villanueva', 4),
(DEFAULT, 'Zambrano', 4),
(DEFAULT, 'Tunja', 5),
(DEFAULT, 'Almeida', 5),
(DEFAULT, 'Aquitania', 5),
(DEFAULT, 'Arcabuco', 5),
(DEFAULT, 'Belen', 5),
(DEFAULT, 'Berbeo', 5),
(DEFAULT, 'Beteitiva', 5),
(DEFAULT, 'Boavita', 5),
(DEFAULT, 'Boyaca', 5),
(DEFAULT, 'Briceño', 5),
(DEFAULT, 'Buenavista', 5),
(DEFAULT, 'Busbanza', 5),
(DEFAULT, 'Caldas', 5),
(DEFAULT, 'Campohermoso', 5),
(DEFAULT, 'Cerinza', 5),
(DEFAULT, 'Chinavita', 5),
(DEFAULT, 'Chiquinquira', 5),
(DEFAULT, 'Chiscas', 5),
(DEFAULT, 'Chita', 5),
(DEFAULT, 'Chitaraque', 5),
(DEFAULT, 'Chivata', 5),
(DEFAULT, 'Cienega', 5),
(DEFAULT, 'Combita', 5),
(DEFAULT, 'Coper', 5),
(DEFAULT, 'Corrales', 5),
(DEFAULT, 'Covarachia', 5),
(DEFAULT, 'Cubara', 5),
(DEFAULT, 'Cucaita', 5),
(DEFAULT, 'Cuitiva', 5),
(DEFAULT, 'Chiquiza', 5),
(DEFAULT, 'Chivor', 5),
(DEFAULT, 'Duitama', 5),
(DEFAULT, 'El Cocuy', 5),
(DEFAULT, 'El Espino', 5),
(DEFAULT, 'Firavitoba', 5),
(DEFAULT, 'Floresta', 5),
(DEFAULT, 'Gachantiva', 5),
(DEFAULT, 'Gameza', 5),
(DEFAULT, 'Garagoa', 5),
(DEFAULT, 'Guacamayas', 5),
(DEFAULT, 'Guateque', 5),
(DEFAULT, 'Guayata', 5),
(DEFAULT, 'Guican', 5),
(DEFAULT, 'Iza', 5),
(DEFAULT, 'Jenesano', 5),
(DEFAULT, 'Jerico', 5),
(DEFAULT, 'Labranzagrande', 5),
(DEFAULT, 'La Capilla', 5),
(DEFAULT, 'La Victoria', 5),
(DEFAULT, 'La Uvita', 5),
(DEFAULT, 'Villa de Leiva', 5),
(DEFAULT, 'Macanal', 5),
(DEFAULT, 'Maripi', 5),
(DEFAULT, 'Miraflores', 5),
(DEFAULT, 'Mongua', 5),
(DEFAULT, 'Mongui', 5),
(DEFAULT, 'Moniquira', 5),
(DEFAULT, 'Motavita', 5),
(DEFAULT, 'Muzo', 5),
(DEFAULT, 'Nobsa', 5),
(DEFAULT, 'Nuevo Colon', 5),
(DEFAULT, 'Oicata', 5),
(DEFAULT, 'Otanche', 5),
(DEFAULT, 'Pachavita', 5),
(DEFAULT, 'Paez', 5),
(DEFAULT, 'Paipa', 5),
(DEFAULT, 'Pajarito', 5),
(DEFAULT, 'Panqueba', 5),
(DEFAULT, 'Pauna', 5),
(DEFAULT, 'Paya', 5),
(DEFAULT, 'Paz del Rio', 5),
(DEFAULT, 'Pesca', 5),
(DEFAULT, 'Pisba', 5),
(DEFAULT, 'Puerto Boyaca', 5),
(DEFAULT, 'Quipama', 5),
(DEFAULT, 'Ramiriqui', 5),
(DEFAULT, 'Raquira', 5),
(DEFAULT, 'Rondon', 5),
(DEFAULT, 'Saboya', 5),
(DEFAULT, 'Sachica', 5),
(DEFAULT, 'Samaca', 5),
(DEFAULT, 'San Eduardo', 5),
(DEFAULT, 'San Jose de Pare', 5),
(DEFAULT, 'San Luis de Gaceno', 5),
(DEFAULT, 'San Mateo', 5),
(DEFAULT, 'San Miguel de Sema', 5),
(DEFAULT, 'San Pablo de Borbur', 5),
(DEFAULT, 'Santana', 5),
(DEFAULT, 'Santa Maria', 5),
(DEFAULT, 'Santa Rosa de Viterbo', 5),
(DEFAULT, 'Santa Sofia', 5),
(DEFAULT, 'Sativanorte', 5),
(DEFAULT, 'Sativasur', 5),
(DEFAULT, 'Siachoque', 5),
(DEFAULT, 'Soata', 5),
(DEFAULT, 'Socota', 5),
(DEFAULT, 'Socha', 5),
(DEFAULT, 'Sogamoso', 5),
(DEFAULT, 'Somondoco', 5),
(DEFAULT, 'Sora', 5),
(DEFAULT, 'Sotaquira', 5),
(DEFAULT, 'Soraca', 5),
(DEFAULT, 'Susacon', 5),
(DEFAULT, 'Sutamarchan', 5),
(DEFAULT, 'Sutatenza', 5),
(DEFAULT, 'Tasco', 5),
(DEFAULT, 'Tenza', 5),
(DEFAULT, 'Tibana', 5),
(DEFAULT, 'Tibasosa', 5),
(DEFAULT, 'Tinjaca', 5),
(DEFAULT, 'Tipacoque', 5),
(DEFAULT, 'Toca', 5),
(DEFAULT, 'Togui', 5),
(DEFAULT, 'Topaga', 5),
(DEFAULT, 'Tota', 5),
(DEFAULT, 'Tunungua', 5),
(DEFAULT, 'Turmeque', 5),
(DEFAULT, 'Tuta', 5),
(DEFAULT, 'Tutasa', 5),
(DEFAULT, 'Umbita', 5),
(DEFAULT, 'Ventaquemada', 5),
(DEFAULT, 'Viracacha', 5),
(DEFAULT, 'Zetaquira', 5),
(DEFAULT, 'Manizales', 6),
(DEFAULT, 'Aguadas', 6),
(DEFAULT, 'Anserma', 6),
(DEFAULT, 'Aranzazu', 6),
(DEFAULT, 'Belalcazar', 6),
(DEFAULT, 'Chinchina', 6),
(DEFAULT, 'Filadelfia', 6),
(DEFAULT, 'La Dorada', 6),
(DEFAULT, 'La Merced', 6),
(DEFAULT, 'Manzanares', 6),
(DEFAULT, 'Marmato', 6),
(DEFAULT, 'Marquetalia', 6),
(DEFAULT, 'Marulanda', 6),
(DEFAULT, 'Neira', 6),
(DEFAULT, 'Norcasia', 6),
(DEFAULT, 'Pacora', 6),
(DEFAULT, 'Palestina', 6),
(DEFAULT, 'Pensilvania', 6),
(DEFAULT, 'Riosucio', 6),
(DEFAULT, 'Risaralda', 6),
(DEFAULT, 'Salamina', 6),
(DEFAULT, 'Samana', 6),
(DEFAULT, 'San Jose', 6),
(DEFAULT, 'Supia', 6),
(DEFAULT, 'Victoria', 6),
(DEFAULT, 'Villamaria', 6),
(DEFAULT, 'Viterbo', 6),
(DEFAULT, 'Florencia', 7),
(DEFAULT, 'Albania', 7),
(DEFAULT, 'Belen de Los Andaquies', 7),
(DEFAULT, 'Cartagena Del Chaira', 7),
(DEFAULT, 'Curillo', 7),
(DEFAULT, 'El Doncello', 7),
(DEFAULT, 'El Paujil', 7),
(DEFAULT, 'La Montañita', 7),
(DEFAULT, 'Milan', 7),
(DEFAULT, 'Morelia', 7),
(DEFAULT, 'Puerto Rico', 7),
(DEFAULT, 'San Jose de Fragua', 7),
(DEFAULT, 'San Vicente del Caguan', 7),
(DEFAULT, 'Solano', 7),
(DEFAULT, 'Solita', 7),
(DEFAULT, 'Valparaiso', 7),
(DEFAULT, 'Popayan', 8),
(DEFAULT, 'Almaguer', 8),
(DEFAULT, 'Argelia', 8),
(DEFAULT, 'Balboa', 8),
(DEFAULT, 'Bolivar', 8),
(DEFAULT, 'Buenos Aires', 8),
(DEFAULT, 'Cajibio', 8),
(DEFAULT, 'Caldono', 8),
(DEFAULT, 'Caloto', 8),
(DEFAULT, 'Corinto', 8),
(DEFAULT, 'El Tambo', 8),
(DEFAULT, 'Florencia', 8),
(DEFAULT, 'Guapi', 8),
(DEFAULT, 'Inza', 8),
(DEFAULT, 'Jambalo', 8),
(DEFAULT, 'La Sierra', 8),
(DEFAULT, 'La Vega', 8),
(DEFAULT, 'Lopez', 8),
(DEFAULT, 'Mercaderes', 8),
(DEFAULT, 'Miranda', 8),
(DEFAULT, 'Morales', 8),
(DEFAULT, 'Padilla', 8),
(DEFAULT, 'Paez', 8),
(DEFAULT, 'Patia', 8),
(DEFAULT, 'Piamonte', 8),
(DEFAULT, 'Piendamo', 8),
(DEFAULT, 'Puerto Tejada', 8),
(DEFAULT, 'Purace', 8),
(DEFAULT, 'Rosas', 8),
(DEFAULT, 'San Sebastian', 8),
(DEFAULT, 'Santander de Quilichao', 8),
(DEFAULT, 'Santa Rosa', 8),
(DEFAULT, 'Silvia', 8),
(DEFAULT, 'Sotara', 8),
(DEFAULT, 'Suarez', 8),
(DEFAULT, 'Timbio', 8),
(DEFAULT, 'Timbiqui', 8),
(DEFAULT, 'Toribio', 8),
(DEFAULT, 'Totoro', 8),
(DEFAULT, 'Villarica', 8),
(DEFAULT, 'Valledupar', 9),
(DEFAULT, 'Aguachica', 9),
(DEFAULT, 'Agustin Codazzi', 9),
(DEFAULT, 'Astrea', 9),
(DEFAULT, 'Becerril', 9),
(DEFAULT, 'Bosconia', 9),
(DEFAULT, 'Chimichagua', 9),
(DEFAULT, 'Chiriguana', 9),
(DEFAULT, 'Curumani', 9),
(DEFAULT, 'El Copey', 9),
(DEFAULT, 'El Paso', 9),
(DEFAULT, 'Gamarra', 9),
(DEFAULT, 'Gonzalez', 9),
(DEFAULT, 'La Gloria', 9),
(DEFAULT, 'La Jagua Ibirico', 9),
(DEFAULT, 'Manaure', 9),
(DEFAULT, 'Pailitas', 9),
(DEFAULT, 'Pelaya', 9),
(DEFAULT, 'Pueblo Bello', 9),
(DEFAULT, 'Rio de Oro', 9),
(DEFAULT, 'La Paz', 9),
(DEFAULT, 'San Alberto', 9),
(DEFAULT, 'San Diego', 9),
(DEFAULT, 'San Martin', 9),
(DEFAULT, 'Tamalameque', 9),
(DEFAULT, 'Monteria', 10),
(DEFAULT, 'Ayapel', 10),
(DEFAULT, 'Buenavista', 10),
(DEFAULT, 'Canalete', 10),
(DEFAULT, 'Cerete', 10),
(DEFAULT, 'Chima', 10),
(DEFAULT, 'Chinu', 10),
(DEFAULT, 'Cienaga de Oro', 10),
(DEFAULT, 'Cotorra', 10),
(DEFAULT, 'La Apartada', 10),
(DEFAULT, 'Lorica', 10),
(DEFAULT, 'Los Cordobas', 10),
(DEFAULT, 'Momil', 10),
(DEFAULT, 'Montelibano', 10),
(DEFAULT, 'Moñitos', 10),
(DEFAULT, 'Planeta Rica', 10),
(DEFAULT, 'Pueblo Nuevo', 10),
(DEFAULT, 'Puerto Escondido', 10),
(DEFAULT, 'Puerto Libertador', 10),
(DEFAULT, 'Purisima', 10),
(DEFAULT, 'Sahagun', 10),
(DEFAULT, 'San Andres Sotavento', 10),
(DEFAULT, 'San Antero', 10),
(DEFAULT, 'San Bernardo del Viento', 10),
(DEFAULT, 'San Carlos', 10),
(DEFAULT, 'San Pelayo', 10),
(DEFAULT, 'Tierralta', 10),
(DEFAULT, 'Valencia', 10),
(DEFAULT, 'Agua de Dios', 11),
(DEFAULT, 'Alban', 11),
(DEFAULT, 'Anapoima', 11),
(DEFAULT, 'Anolaima', 11),
(DEFAULT, 'Arbelaez', 11),
(DEFAULT, 'Beltran', 11),
(DEFAULT, 'Bituima', 11),
(DEFAULT, 'Bojaca', 11),
(DEFAULT, 'Cabrera', 11),
(DEFAULT, 'Cachipay', 11),
(DEFAULT, 'Cajica', 11),
(DEFAULT, 'Caparrapi', 11),
(DEFAULT, 'Caqueza', 11),
(DEFAULT, 'Carmen de Carupa', 11),
(DEFAULT, 'Chaguani', 11),
(DEFAULT, 'Chia', 11),
(DEFAULT, 'Chipaque', 11),
(DEFAULT, 'Choachi', 11),
(DEFAULT, 'Choconta', 11),
(DEFAULT, 'Cogua', 11),
(DEFAULT, 'Cota', 11),
(DEFAULT, 'Cucunuba', 11),
(DEFAULT, 'El Colegio', 11),
(DEFAULT, 'El Peñon', 11),
(DEFAULT, 'El Rosal', 11),
(DEFAULT, 'Facatativa', 11),
(DEFAULT, 'Fomeque', 11),
(DEFAULT, 'Fosca', 11),
(DEFAULT, 'Funza', 11),
(DEFAULT, 'Fuquene', 11),
(DEFAULT, 'Fusagasuga', 11),
(DEFAULT, 'Gachala', 11),
(DEFAULT, 'Gachancipa', 11),
(DEFAULT, 'Gacheta', 11),
(DEFAULT, 'Gama', 11),
(DEFAULT, 'Girardot', 11),
(DEFAULT, 'Granada', 11),
(DEFAULT, 'Guacheta', 11),
(DEFAULT, 'Guaduas', 11),
(DEFAULT, 'Guasca', 11),
(DEFAULT, 'Guataqui', 11),
(DEFAULT, 'Guatavita', 11),
(DEFAULT, 'Guayabal de Siquima', 11),
(DEFAULT, 'Guayabetal', 11),
(DEFAULT, 'Gutierrez', 11),
(DEFAULT, 'Jerusalen', 11),
(DEFAULT, 'Junin', 11),
(DEFAULT, 'La Calera', 11),
(DEFAULT, 'La Mesa', 11),
(DEFAULT, 'La Palma', 11),
(DEFAULT, 'La Peña', 11),
(DEFAULT, 'La Vega', 11),
(DEFAULT, 'Lenguazaque', 11),
(DEFAULT, 'Macheta', 11),
(DEFAULT, 'Madrid', 11),
(DEFAULT, 'Manta', 11),
(DEFAULT, 'Medina', 11),
(DEFAULT, 'Mosquera', 11),
(DEFAULT, 'Nariño', 11),
(DEFAULT, 'Nemocon', 11),
(DEFAULT, 'Nilo', 11),
(DEFAULT, 'Nimaima', 11),
(DEFAULT, 'Nocaima', 11),
(DEFAULT, 'Venecia', 11),
(DEFAULT, 'Pacho', 11),
(DEFAULT, 'Paime', 11),
(DEFAULT, 'Pandi', 11),
(DEFAULT, 'Paratebueno', 11),
(DEFAULT, 'Pasca', 11),
(DEFAULT, 'Puerto Salgar', 11),
(DEFAULT, 'Puli', 11),
(DEFAULT, 'Quebradanegra', 11),
(DEFAULT, 'Quetame', 11),
(DEFAULT, 'Quipile', 11),
(DEFAULT, 'Apulo', 11),
(DEFAULT, 'Ricaurte', 11),
(DEFAULT, 'San Antonio del Tequendama', 11),
(DEFAULT, 'San Bernardo', 11),
(DEFAULT, 'San Cayetano', 11),
(DEFAULT, 'San Francisco', 11),
(DEFAULT, 'San Juan de Rioseco', 11),
(DEFAULT, 'Sasaima', 11),
(DEFAULT, 'Sesquile', 11),
(DEFAULT, 'Sibate', 11),
(DEFAULT, 'Silvania', 11),
(DEFAULT, 'Simijaca', 11),
(DEFAULT, 'Soacha', 11),
(DEFAULT, 'Sopo', 11),
(DEFAULT, 'Subachoque', 11),
(DEFAULT, 'Suesca', 11),
(DEFAULT, 'Supata', 11),
(DEFAULT, 'Susa', 11),
(DEFAULT, 'Sutatausa', 11),
(DEFAULT, 'Tabio', 11),
(DEFAULT, 'Tausa', 11),
(DEFAULT, 'Tena', 11),
(DEFAULT, 'Tenjo', 11),
(DEFAULT, 'Tibacuy', 11),
(DEFAULT, 'Tibirita', 11),
(DEFAULT, 'Tocaima', 11),
(DEFAULT, 'Tocancipa', 11),
(DEFAULT, 'Topaipi', 11),
(DEFAULT, 'Ubala', 11),
(DEFAULT, 'Ubaque', 11),
(DEFAULT, 'Ubate', 11),
(DEFAULT, 'Une', 11),
(DEFAULT, 'Utica', 11),
(DEFAULT, 'Vergara', 11),
(DEFAULT, 'Viani', 11),
(DEFAULT, 'Villagomez', 11),
(DEFAULT, 'Villapinzon', 11),
(DEFAULT, 'Villeta', 11),
(DEFAULT, 'Viota', 11),
(DEFAULT, 'Yacopi', 11),
(DEFAULT, 'Zipacon', 11),
(DEFAULT, 'Zipaquira', 11),
(DEFAULT, 'Quibdo', 12),
(DEFAULT, 'Acandi', 12),
(DEFAULT, 'Alto Baudo', 12),
(DEFAULT, 'Atrato', 12),
(DEFAULT, 'Bagado', 12),
(DEFAULT, 'Bahia Solano', 12),
(DEFAULT, 'Bajo Baudo', 12),
(DEFAULT, 'Bojaya', 12),
(DEFAULT, 'Canton de San Pablo', 12),
(DEFAULT, 'Condoto', 12),
(DEFAULT, 'El Carmen de Atrato', 12),
(DEFAULT, 'Litoral del Bajo San Juan', 12),
(DEFAULT, 'Istmina', 12),
(DEFAULT, 'Jurado', 12),
(DEFAULT, 'Lloro', 12),
(DEFAULT, 'Medio Atrato', 12),
(DEFAULT, 'Medio Baudo', 12),
(DEFAULT, 'Novita', 12),
(DEFAULT, 'Nuqui', 12),
(DEFAULT, 'Rioquito', 12),
(DEFAULT, 'Riosucio', 12),
(DEFAULT, 'San Jose del Palmar', 12),
(DEFAULT, 'Sipi', 12),
(DEFAULT, 'Tado', 12),
(DEFAULT, 'Unguia', 12),
(DEFAULT, 'Union Panamericana', 12),
(DEFAULT, 'Neiva', 13),
(DEFAULT, 'Acevedo', 13),
(DEFAULT, 'Agrado', 13),
(DEFAULT, 'Aipe', 13),
(DEFAULT, 'Algeciras', 13),
(DEFAULT, 'Altamira', 13),
(DEFAULT, 'Baraya', 13),
(DEFAULT, 'Campoalegre', 13),
(DEFAULT, 'Colombia', 13),
(DEFAULT, 'Elias', 13),
(DEFAULT, 'Garzon', 13),
(DEFAULT, 'Gigante', 13),
(DEFAULT, 'Guadalupe', 13),
(DEFAULT, 'Hobo', 13),
(DEFAULT, 'Iquira', 13),
(DEFAULT, 'Isnos', 13),
(DEFAULT, 'La Argentina', 13),
(DEFAULT, 'La Plata', 13),
(DEFAULT, 'Nataga', 13),
(DEFAULT, 'Oporapa', 13),
(DEFAULT, 'Paicol', 13),
(DEFAULT, 'Palermo', 13),
(DEFAULT, 'Palestina', 13),
(DEFAULT, 'Pital', 13),
(DEFAULT, 'Pitalito', 13),
(DEFAULT, 'Rivera', 13),
(DEFAULT, 'Saladoblanco', 13),
(DEFAULT, 'San Agustin', 13),
(DEFAULT, 'Santa Maria', 13),
(DEFAULT, 'Suaza', 13),
(DEFAULT, 'Tarqui', 13),
(DEFAULT, 'Tesalia', 13),
(DEFAULT, 'Tello', 13),
(DEFAULT, 'Teruel', 13),
(DEFAULT, 'Timana', 13),
(DEFAULT, 'Villavieja', 13),
(DEFAULT, 'Yaguara', 13),
(DEFAULT, 'Riohacha', 14),
(DEFAULT, 'Barrancas', 14),
(DEFAULT, 'Dibulla', 14),
(DEFAULT, 'Distraccion', 14),
(DEFAULT, 'El Molino', 14),
(DEFAULT, 'Fonseca', 14),
(DEFAULT, 'Hatonuevo', 14),
(DEFAULT, 'La Jagua del Pilar', 14),
(DEFAULT, 'Maicao', 14),
(DEFAULT, 'Manaure', 14),
(DEFAULT, 'San Juan del Cesar', 14),
(DEFAULT, 'Uribia', 14),
(DEFAULT, 'Urumita', 14),
(DEFAULT, 'Villanueva', 14),
(DEFAULT, 'Santa Marta', 15),
(DEFAULT, 'Algarrobo', 15),
(DEFAULT, 'Aracataca', 15),
(DEFAULT, 'Ariguani', 15),
(DEFAULT, 'Cerro San Antonio', 15),
(DEFAULT, 'Chivolo', 15),
(DEFAULT, 'Cienaga', 15),
(DEFAULT, 'Concordia', 15),
(DEFAULT, 'El Banco', 15),
(DEFAULT, 'El Piñon', 15),
(DEFAULT, 'El Reten', 15),
(DEFAULT, 'Fundacion', 15),
(DEFAULT, 'Guamal', 15),
(DEFAULT, 'Pedraza', 15),
(DEFAULT, 'Pijiño del Carmen', 15),
(DEFAULT, 'Pivijay', 15),
(DEFAULT, 'Plato', 15),
(DEFAULT, 'Puebloviejo', 15),
(DEFAULT, 'Remolino', 15),
(DEFAULT, 'Sabanas de San Angel', 15),
(DEFAULT, 'Salamina', 15),
(DEFAULT, 'San Sebastian de Buenavista', 15),
(DEFAULT, 'San Zenon', 15),
(DEFAULT, 'Santa Ana', 15),
(DEFAULT, 'Sitionuevo', 15),
(DEFAULT, 'Tenerife', 15),
(DEFAULT, 'Villavicencio', 16),
(DEFAULT, 'Acacias', 16),
(DEFAULT, 'Barranca de Upia', 16),
(DEFAULT, 'Cabuyaro', 16),
(DEFAULT, 'Castilla La Nueva', 16),
(DEFAULT, 'San Luis de Cubarral', 16),
(DEFAULT, 'Cumaral', 16),
(DEFAULT, 'El Calvario', 16),
(DEFAULT, 'El Castillo', 16),
(DEFAULT, 'El Dorado', 16),
(DEFAULT, 'Fuente de Oro', 16),
(DEFAULT, 'Granada', 16),
(DEFAULT, 'Guamal', 16),
(DEFAULT, 'Mapiripan', 16),
(DEFAULT, 'Mesetas', 16),
(DEFAULT, 'La Macarena', 16),
(DEFAULT, 'La Uribe', 16),
(DEFAULT, 'Lejanias', 16),
(DEFAULT, 'Puerto Concordia', 16),
(DEFAULT, 'Puerto Gaitan', 16),
(DEFAULT, 'Puerto Lopez', 16),
(DEFAULT, 'Puerto Lleras', 16),
(DEFAULT, 'Puerto Rico', 16),
(DEFAULT, 'Restrepo', 16),
(DEFAULT, 'San Carlos de Guaroa', 16),
(DEFAULT, 'San Juan de Arama', 16),
(DEFAULT, 'San Juanito', 16),
(DEFAULT, 'San Martin', 16),
(DEFAULT, 'Vistahermosa', 16),
(DEFAULT, 'Pasto', 17),
(DEFAULT, 'Alban', 17),
(DEFAULT, 'Aldana', 17),
(DEFAULT, 'Ancuya', 17),
(DEFAULT, 'Arboleda', 17),
(DEFAULT, 'Barbacoas', 17),
(DEFAULT, 'Belen', 17),
(DEFAULT, 'Buesaco', 17),
(DEFAULT, 'Colon', 17),
(DEFAULT, 'Consaca', 17),
(DEFAULT, 'Contadero', 17),
(DEFAULT, 'Cordoba', 17),
(DEFAULT, 'Cuaspud', 17),
(DEFAULT, 'Cumbal', 17),
(DEFAULT, 'Cumbitara', 17),
(DEFAULT, 'Chachagui', 17),
(DEFAULT, 'El Charco', 17),
(DEFAULT, 'El Peñol', 17),
(DEFAULT, 'El Rosario', 17),
(DEFAULT, 'El Tablon', 17),
(DEFAULT, 'El Tambo', 17),
(DEFAULT, 'Funes', 17),
(DEFAULT, 'Guachucal', 17),
(DEFAULT, 'Guaitarilla', 17),
(DEFAULT, 'Gualmatan', 17),
(DEFAULT, 'Iles', 17),
(DEFAULT, 'Imues', 17),
(DEFAULT, 'Ipiales', 17),
(DEFAULT, 'La Cruz', 17),
(DEFAULT, 'La Florida', 17),
(DEFAULT, 'La Llanada', 17),
(DEFAULT, 'La Tola', 17),
(DEFAULT, 'La Union', 17),
(DEFAULT, 'Leiva', 17),
(DEFAULT, 'Linares', 17),
(DEFAULT, 'Los Andes', 17),
(DEFAULT, 'Magui', 17),
(DEFAULT, 'Mallama', 17),
(DEFAULT, 'Mosquera', 17),
(DEFAULT, 'Olaya Herrera', 17),
(DEFAULT, 'Ospina', 17),
(DEFAULT, 'Francisco Pizarro', 17),
(DEFAULT, 'Policarpa', 17),
(DEFAULT, 'Potosi', 17),
(DEFAULT, 'Providencia', 17),
(DEFAULT, 'Puerres', 17),
(DEFAULT, 'Pupiales', 17),
(DEFAULT, 'Ricaurte', 17),
(DEFAULT, 'Roberto Payan', 17),
(DEFAULT, 'Samaniego', 17),
(DEFAULT, 'Sandona', 17),
(DEFAULT, 'San Bernardo', 17),
(DEFAULT, 'San Lorenzo', 17),
(DEFAULT, 'San Pablo', 17),
(DEFAULT, 'San Pedro de Cartago', 17),
(DEFAULT, 'Santa Barbara', 17),
(DEFAULT, 'Santa Cruz', 17),
(DEFAULT, 'Sapuyes', 17),
(DEFAULT, 'Taminango', 17),
(DEFAULT, 'Tangua', 17),
(DEFAULT, 'Tumaco', 17),
(DEFAULT, 'Tuquerres', 17),
(DEFAULT, 'Yacuanquer', 17),
(DEFAULT, 'Cucuta', 18),
(DEFAULT, 'Abrego', 18),
(DEFAULT, 'Arboledas', 18),
(DEFAULT, 'Bochalema', 18),
(DEFAULT, 'Bucarasica', 18),
(DEFAULT, 'Cacota', 18),
(DEFAULT, 'Cachira', 18),
(DEFAULT, 'Chinacota', 18),
(DEFAULT, 'Chitaga', 18),
(DEFAULT, 'Convencion', 18),
(DEFAULT, 'Cucutilla', 18),
(DEFAULT, 'Durania', 18),
(DEFAULT, 'El Carmen', 18),
(DEFAULT, 'El Tarra', 18),
(DEFAULT, 'El Zulia', 18),
(DEFAULT, 'Gramalote', 18),
(DEFAULT, 'Hacari', 18),
(DEFAULT, 'Herran', 18),
(DEFAULT, 'Labateca', 18),
(DEFAULT, 'La Esperanza', 18),
(DEFAULT, 'La Playa', 18),
(DEFAULT, 'Los Patios', 18),
(DEFAULT, 'Lourdes', 18),
(DEFAULT, 'Mutiscua', 18),
(DEFAULT, 'Ocaña', 18),
(DEFAULT, 'Pamplona', 18),
(DEFAULT, 'Pamplonita', 18),
(DEFAULT, 'Puerto Santander', 18),
(DEFAULT, 'Ragonvalia', 18),
(DEFAULT, 'Salazar', 18),
(DEFAULT, 'San Calixto', 18),
(DEFAULT, 'San Cayetano', 18),
(DEFAULT, 'Santiago', 18),
(DEFAULT, 'Sardinata', 18),
(DEFAULT, 'Silos', 18),
(DEFAULT, 'Teorama', 18),
(DEFAULT, 'Tibu', 18),
(DEFAULT, 'Toledo', 18),
(DEFAULT, 'Villacaro', 18),
(DEFAULT, 'Villa del Rosario', 18),
(DEFAULT, 'Armenia', 19),
(DEFAULT, 'Buenavista', 19),
(DEFAULT, 'Calarca', 19),
(DEFAULT, 'Circasia', 19),
(DEFAULT, 'Cordoba', 19),
(DEFAULT, 'Filandia', 19),
(DEFAULT, 'Genova', 19),
(DEFAULT, 'La Tebaida', 19),
(DEFAULT, 'Montenegro', 19),
(DEFAULT, 'Pijao', 19),
(DEFAULT, 'Quimbaya', 19),
(DEFAULT, 'Salento', 19),
(DEFAULT, 'Pereira', 20),
(DEFAULT, 'Apia', 20),
(DEFAULT, 'Balboa', 20),
(DEFAULT, 'Belen de Umbria', 20),
(DEFAULT, 'Dos Quebradas', 20),
(DEFAULT, 'Guatica', 20),
(DEFAULT, 'La Celia', 20),
(DEFAULT, 'La Virginia', 20),
(DEFAULT, 'Marsella', 20),
(DEFAULT, 'Mistrato', 20),
(DEFAULT, 'Pueblo Rico', 20),
(DEFAULT, 'Quinchia', 20),
(DEFAULT, 'Santa Rosa de Cabal', 20),
(DEFAULT, 'Santuario', 20),
(DEFAULT, 'Bucaramanga', 21),
(DEFAULT, 'Aguada', 21),
(DEFAULT, 'Albania', 21),
(DEFAULT, 'Aratoca', 21),
(DEFAULT, 'Barbosa', 21),
(DEFAULT, 'Barichara', 21),
(DEFAULT, 'Barrancabermeja', 21),
(DEFAULT, 'Betulia', 21),
(DEFAULT, 'Bolivar', 21),
(DEFAULT, 'Cabrera', 21),
(DEFAULT, 'California', 21),
(DEFAULT, 'Capitanejo', 21),
(DEFAULT, 'Carcasi', 21),
(DEFAULT, 'Cepita', 21),
(DEFAULT, 'Cerrito', 21),
(DEFAULT, 'Charala', 21),
(DEFAULT, 'Charta', 21),
(DEFAULT, 'Chima', 21),
(DEFAULT, 'Chipata', 21),
(DEFAULT, 'Cimitarra', 21),
(DEFAULT, 'Concepcion', 21),
(DEFAULT, 'Confines', 21),
(DEFAULT, 'Contratacion', 21),
(DEFAULT, 'Coromoro', 21),
(DEFAULT, 'Curiti', 21),
(DEFAULT, 'El Carmen de Chucury', 21),
(DEFAULT, 'El Guacamayo', 21),
(DEFAULT, 'El Peñon', 21),
(DEFAULT, 'El Playon', 21),
(DEFAULT, 'Encino', 21),
(DEFAULT, 'Enciso', 21),
(DEFAULT, 'Florian', 21),
(DEFAULT, 'Floridablanca', 21),
(DEFAULT, 'Galan', 21),
(DEFAULT, 'Gambita', 21),
(DEFAULT, 'Giron', 21),
(DEFAULT, 'Guaca', 21),
(DEFAULT, 'Guadalupe', 21),
(DEFAULT, 'Guapota', 21),
(DEFAULT, 'Guavata', 21),
(DEFAULT, 'Guepsa', 21),
(DEFAULT, 'Hato', 21),
(DEFAULT, 'Jesus Maria', 21),
(DEFAULT, 'Jordan', 21),
(DEFAULT, 'La Belleza', 21),
(DEFAULT, 'Landazuri', 21),
(DEFAULT, 'La Paz', 21),
(DEFAULT, 'Lebrija', 21),
(DEFAULT, 'Los Santos', 21),
(DEFAULT, 'Macaravita', 21),
(DEFAULT, 'Malaga', 21),
(DEFAULT, 'Matanza', 21),
(DEFAULT, 'Mogotes', 21),
(DEFAULT, 'Molagavita', 21),
(DEFAULT, 'Ocamonte', 21),
(DEFAULT, 'Oiba', 21),
(DEFAULT, 'Onzaga', 21),
(DEFAULT, 'Palmar', 21),
(DEFAULT, 'Palmas del Socorro', 21),
(DEFAULT, 'Paramo', 21),
(DEFAULT, 'Piedecuesta', 21),
(DEFAULT, 'Pinchote', 21),
(DEFAULT, 'Puente Nacional', 21),
(DEFAULT, 'Puerto Parra', 21),
(DEFAULT, 'Puerto Wilches', 21),
(DEFAULT, 'Rionegro', 21),
(DEFAULT, 'Sabana de Torres', 21),
(DEFAULT, 'San Andres', 21),
(DEFAULT, 'San Benito', 21),
(DEFAULT, 'San Gil', 21),
(DEFAULT, 'San Joaquin', 21),
(DEFAULT, 'San Jose de Miranda', 21),
(DEFAULT, 'San Miguel', 21),
(DEFAULT, 'San Vicente de Chucuri', 21),
(DEFAULT, 'Santa Barbara', 21),
(DEFAULT, 'Santa Helena del Opon', 21),
(DEFAULT, 'Simacota', 21),
(DEFAULT, 'Socorro', 21),
(DEFAULT, 'Suaita', 21),
(DEFAULT, 'Sucre', 21),
(DEFAULT, 'Surata', 21),
(DEFAULT, 'Tona', 21),
(DEFAULT, 'Valle San Jose', 21),
(DEFAULT, 'Velez', 21),
(DEFAULT, 'Vetas', 21),
(DEFAULT, 'Villanueva', 21),
(DEFAULT, 'Zapatoca', 21),
(DEFAULT, 'Sincelejo', 22),
(DEFAULT, 'Buenavista', 22),
(DEFAULT, 'Caimito', 22),
(DEFAULT, 'Coloso', 22),
(DEFAULT, 'Corozal', 22),
(DEFAULT, 'Chalan', 22),
(DEFAULT, 'Galeras', 22),
(DEFAULT, 'Guaranda', 22),
(DEFAULT, 'La Union', 22),
(DEFAULT, 'Los Palmitos', 22),
(DEFAULT, 'Majagual', 22),
(DEFAULT, 'Morroa', 22),
(DEFAULT, 'Ovejas', 22),
(DEFAULT, 'Palmito', 22),
(DEFAULT, 'Sampues', 22),
(DEFAULT, 'San Benito Abad', 22),
(DEFAULT, 'San Juan de Betulia', 22),
(DEFAULT, 'San Marcos', 22),
(DEFAULT, 'San Onofre', 22),
(DEFAULT, 'San Pedro', 22),
(DEFAULT, 'Since', 22),
(DEFAULT, 'Sucre', 22),
(DEFAULT, 'Tolu', 22),
(DEFAULT, 'Toluviejo', 22),
(DEFAULT, 'Ibague', 23),
(DEFAULT, 'Alpujarra', 23),
(DEFAULT, 'Alvarado', 23),
(DEFAULT, 'Ambalema', 23),
(DEFAULT, 'Anzoategui', 23),
(DEFAULT, 'Armero', 23),
(DEFAULT, 'Ataco', 23),
(DEFAULT, 'Cajamarca', 23),
(DEFAULT, 'Carmen Apicala', 23),
(DEFAULT, 'Casabianca', 23),
(DEFAULT, 'Chaparral', 23),
(DEFAULT, 'Coello', 23),
(DEFAULT, 'Coyaima', 23),
(DEFAULT, 'Cunday', 23),
(DEFAULT, 'Dolores', 23),
(DEFAULT, 'Espinal', 23),
(DEFAULT, 'Falan', 23),
(DEFAULT, 'Flandes', 23),
(DEFAULT, 'Fresno', 23),
(DEFAULT, 'Guamo', 23),
(DEFAULT, 'Herveo', 23),
(DEFAULT, 'Honda', 23),
(DEFAULT, 'Icononzo', 23),
(DEFAULT, 'Lerida', 23),
(DEFAULT, 'Libano', 23),
(DEFAULT, 'Mariquita', 23),
(DEFAULT, 'Melgar', 23),
(DEFAULT, 'Murillo', 23),
(DEFAULT, 'Natagaima', 23),
(DEFAULT, 'Ortega', 23),
(DEFAULT, 'Palocabildo', 23),
(DEFAULT, 'Piedras', 23),
(DEFAULT, 'Planadas', 23),
(DEFAULT, 'Prado', 23),
(DEFAULT, 'Purificacion', 23),
(DEFAULT, 'Rioblanco', 23),
(DEFAULT, 'Roncesvalles', 23),
(DEFAULT, 'Rovira', 23),
(DEFAULT, 'Saldaña', 23),
(DEFAULT, 'San Antonio', 23),
(DEFAULT, 'San Luis', 23),
(DEFAULT, 'Santa Isabel', 23),
(DEFAULT, 'Suarez', 23),
(DEFAULT, 'Valle de San Juan', 23),
(DEFAULT, 'Venadillo', 23),
(DEFAULT, 'Villahermosa', 23),
(DEFAULT, 'Villarrica', 23),
(DEFAULT, 'Santiago de Cali', 24),
(DEFAULT, 'Alcala', 24),
(DEFAULT, 'Andalucia', 24),
(DEFAULT, 'Ansermanuevo', 24),
(DEFAULT, 'Argelia', 24),
(DEFAULT, 'Bolivar', 24),
(DEFAULT, 'Buenaventura', 24),
(DEFAULT, 'Buga', 24),
(DEFAULT, 'Bugalagrande', 24),
(DEFAULT, 'Caicedonia', 24),
(DEFAULT, 'Calima', 24),
(DEFAULT, 'Candelaria', 24),
(DEFAULT, 'Cartago', 24),
(DEFAULT, 'Dagua', 24),
(DEFAULT, 'El Aguila', 24),
(DEFAULT, 'El Cairo', 24),
(DEFAULT, 'El Cerrito', 24),
(DEFAULT, 'El Dovio', 24),
(DEFAULT, 'Florida', 24),
(DEFAULT, 'Ginebra', 24),
(DEFAULT, 'Guacari', 24),
(DEFAULT, 'Jamundi', 24),
(DEFAULT, 'La Cumbre', 24),
(DEFAULT, 'La Union', 24),
(DEFAULT, 'La Victoria', 24),
(DEFAULT, 'Obando', 24),
(DEFAULT, 'Palmira', 24),
(DEFAULT, 'Pradera', 24),
(DEFAULT, 'Restrepo', 24),
(DEFAULT, 'Riofrio', 24),
(DEFAULT, 'Roldanillo', 24),
(DEFAULT, 'San Pedro', 24),
(DEFAULT, 'Sevilla', 24),
(DEFAULT, 'Toro', 24),
(DEFAULT, 'Trujillo', 24),
(DEFAULT, 'Tulua', 24),
(DEFAULT, 'Ulloa', 24),
(DEFAULT, 'Versalles', 24),
(DEFAULT, 'Vijes', 24),
(DEFAULT, 'Yotoco', 24),
(DEFAULT, 'Yumbo', 24),
(DEFAULT, 'Zarzal', 24),
(DEFAULT, 'Arauca', 25),
(DEFAULT, 'Arauquita', 25),
(DEFAULT, 'Cravo Norte', 25),
(DEFAULT, 'Fortul', 25),
(DEFAULT, 'Puerto Rondon', 25),
(DEFAULT, 'Saravena', 25),
(DEFAULT, 'Tame', 25),
(DEFAULT, 'Yopal', 26),
(DEFAULT, 'Aguazul', 26),
(DEFAULT, 'Chameza', 26),
(DEFAULT, 'Hato Corozal', 26),
(DEFAULT, 'La Salina', 26),
(DEFAULT, 'Mani', 26),
(DEFAULT, 'Monterrey', 26),
(DEFAULT, 'Nunchia', 26),
(DEFAULT, 'Orocue', 26),
(DEFAULT, 'Paz de Ariporo', 26),
(DEFAULT, 'Pore', 26),
(DEFAULT, 'Recetor', 26),
(DEFAULT, 'Sabanalarga', 26),
(DEFAULT, 'Sacama', 26),
(DEFAULT, 'San Luis de Palenque', 26),
(DEFAULT, 'Tamara', 26),
(DEFAULT, 'Tauramena', 26),
(DEFAULT, 'Trinidad', 26),
(DEFAULT, 'Villanueva', 26),
(DEFAULT, 'Mocoa', 27),
(DEFAULT, 'Colon', 27),
(DEFAULT, 'Orito', 27),
(DEFAULT, 'Puerto Asis', 27),
(DEFAULT, 'Puerto Caicedo', 27),
(DEFAULT, 'Puerto Guzman', 27),
(DEFAULT, 'Puerto Leguizamo', 27),
(DEFAULT, 'Sibundoy', 27),
(DEFAULT, 'San Francisco', 27),
(DEFAULT, 'San Miguel', 27),
(DEFAULT, 'Santiago', 27),
(DEFAULT, 'La Hormiga', 27),
(DEFAULT, 'Villagarzon', 27),
(DEFAULT, 'San Andres', 28),
(DEFAULT, 'Providencia', 28),
(DEFAULT, 'Leticia', 29),
(DEFAULT, 'El Encanto', 29),
(DEFAULT, 'La Chorrera', 29),
(DEFAULT, 'La Pedrera', 29),
(DEFAULT, 'La Victoria', 29),
(DEFAULT, 'Miriti-Parana', 29),
(DEFAULT, 'Puerto Alegria', 29),
(DEFAULT, 'Puerto Arica', 29),
(DEFAULT, 'Puerto Nariño', 29),
(DEFAULT, 'Puerto Santander', 29),
(DEFAULT, 'Tarapaca', 29),
(DEFAULT, 'Puerto Inirida', 30),
(DEFAULT, 'Barranco Minas', 30),
(DEFAULT, 'San Felipe', 30),
(DEFAULT, 'Puerto Colombia', 30),
(DEFAULT, 'La Guadalupe', 30),
(DEFAULT, 'Cacahual', 30),
(DEFAULT, 'Pana Pana', 30),
(DEFAULT, 'Morichal', 30),
(DEFAULT, 'San Jose del Guaviare', 31),
(DEFAULT, 'Calamar', 31),
(DEFAULT, 'El Retorno', 31),
(DEFAULT, 'Miraflores', 31),
(DEFAULT, 'Mitu', 32),
(DEFAULT, 'Caruru', 32),
(DEFAULT, 'Pacoa', 32),
(DEFAULT, 'Taraira', 32),
(DEFAULT, 'Papunaua', 32),
(DEFAULT, 'Yavarate', 32),
(DEFAULT, 'Puerto Carreño', 33),
(DEFAULT, 'La Primavera', 33),
(DEFAULT, 'Santa Rita', 33),
(DEFAULT, 'Santa Rosalia', 33),
(DEFAULT, 'San Jose De Ocune', 33),
(DEFAULT, 'Cumaribo', 33);

INSERT INTO centros_educativos VALUES
(DEFAULT, 'No aplica', 'No aplica', 'No aplica'),
(DEFAULT, 'Colegio Santo Tomas', 'Palmira', 'Privado'),
(DEFAULT, 'Colegio Cardenas', 'Centro', 'Público'),
(DEFAULT, 'Liceo Madre Elisa', 'Palmira', 'Privado'),
(DEFAULT, 'Colegio La Milagrosa', 'Centro', 'Público'),
(DEFAULT, 'Colegio Comfandi', 'Palmira', 'Privado'),
(DEFAULT, 'CENAL', 'Palmira', 'Privado'),
(DEFAULT, 'SENA', 'Palmira', 'Público'),
(DEFAULT, 'Corporación Universitaria Remington', 'Palmira', 'Privado'),
(DEFAULT, 'Fundación Universitaria San Martín', 'Palmira', 'Privado'),
(DEFAULT, 'Universidad Antonio Nariño', 'Palmira', 'Privado'),
(DEFAULT, 'Universidad Nacional Abierta y a Distancia', 'Palmira', 'Privado'),
(DEFAULT, 'Universidad Nacional de Colombia', 'Palmira', 'Público'),
(DEFAULT, 'Universidad Pontificia Bolivariana', 'Palmira', 'Privado'),
(DEFAULT, 'Universidad Autonoma de Occidente', 'Cali', 'Privado'),
(DEFAULT, 'Universidad ICESI', 'Cali', 'Privado'),
(DEFAULT, 'Universidad del Valle', 'Sede Melendez', 'Público'),
(DEFAULT, 'Universidad del Valle', 'Sede San Fernando', 'Público'),
(DEFAULT, 'Universidad del Valle', 'Palmira', 'Público'),
(DEFAULT, 'Universidad Santiago de Cali', 'Cali', 'Privado'),
(DEFAULT, 'Universidad Santiago de Cali', 'Palmira', 'Privado');